#!/bin/sh
set -eux

ip_addr=$(hostname -I | awk '{print $1}')
script_name=$(basename "${0}")
script_dir=$(realpath $(dirname "${0}"))

# Process command options
while getopts "t:e:" opt
do
   case "$opt" in
      t ) target_host="$OPTARG" ;;
      e ) workspace="$OPTARG" ;;
   esac
done

sudo scp swarm@"$target_host":/opt/hpe/swarm-learning-hpe/workspace/"$workspace"/cert/ca/capath/ca-"$target_host"-cert.pem workspace/"$workspace"/cert/ca/capath